## Fichier : docker-compose.yml
version: '3'
services:
  react-docker:
    container_name: react-docker
    build:
      context: ./react-docker
    ports:
      - "3000:3000"
    # stdin_open: true
    volumes:
       - ./react-docker:/usr/src/app/react-docker
       - /usr/src/app/react-docker/node_modules